### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by suhlig** [AdvancedClimateSystems/io#9]
I just wanted to report that I tested your code on a Raspberry Pi, and it works beautifully.

Thank you very much, and keep up the good work!

**Comment by OrangeTux** [comment]
Great to hear! Out of curiosity, for wat purpose are you using this project?

**Comment by suhlig** [comment]
I am using an MCP3008 that is going to read a sensor that measures the current flowing into the LEDs of my [word clock](https://github.com/suhlig/wordclock) (work in progress).
